[package]
name = "spn-is-prime-program"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "spn-is-prime-program"
path = "src/main.rs"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", branch = "dev" }